### ISSUE TITLE
CloudFoundry deployment on PCF Dev

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-cloud#11]
Hi @odedia. I'm trying to deploy the app on a `PCF Dev` instance by following the `readme.md`. I'm new to Cloud Foundry.
The first line of the `deployToCloudFoundry.sh`script is failing. Did you have any idea?

```
arey@MacBook scripts % cf create-service -c '{ "git": { "uri": "https://github.com/arey/spring-petclinic-cloud-config.git", "periodic": true }, "count": 3 }' p.config-server standard config
Création de l'instance de service config dans l'organisation cfdev-org/l'espace cfdev-space en tant que admin...
Service offering 'p.config-server' not found.
ECHEC
```
```
arey@MacBook scripts % cf dev version  
CLI: 0.0.18
BUILD: 36 (f58f3cc)
cf: v13.2.0
cf-mysql: 36.19.0
```

**Comment by odedia** [comment]
Hi,
Can you try running 

cf dev deploy-service scs
Also, on pcf  dev it might be p-confit-server as per docs:

https://docs.pivotal.io/pcf-dev/usage-scs.html

**Comment by arey** [comment]
Thank you @odedia. Unfortunately, my laptop does not have enough ressources to start PCF Dev with Spring Cloud Services :(

**Comment by odedia** [comment]
Bummer. Perhaps a VM in the public cloud?

By the way - I have an idea to replatform the solution for Azure Spring Cloud as well. It’s great that we decided on spring-petclinic-cloud, fits nicely :).

**Comment by arey** [comment]
Great, I saw the Microsoft announcement: https://azure.microsoft.com/fr-fr/services/spring-cloud/

**Comment by arey** [comment]
I've create the issue https://github.com/spring-petclinic/spring-petclinic-cloud/issues/17
