### ISSUE TITLE
Align k8s namespace to spring-petclinic

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-cloud#15]
I propose to change the k8s namespace from `namespace/spring-pet-clinic` to `namespace/spring-petclinic-cloud`

**Comment by odedia** [comment]
I'm fine with both, a Kubernetes namespace implies it's running on cloud anyway but it's not that critical.

**Comment by arey** [comment]
You're right, on real environment it does not matter. But on developer laptop, with `microk8s` or `minikube` we could have name collision. 

I've noticed that k8s yaml files are using or referencing the `spring-petclinic` namespace. See https://github.com/spring-petclinic/spring-petclinic-cloud/blob/master/k8s/init-namespace/01-namespace.yaml and https://github.com/spring-petclinic/spring-petclinic-cloud/blob/master/k8s/init-services/05-api-gateway-service.yaml
I'm a bit lost. Do we have to align all those names?

**Comment by odedia** [comment]
That is correct... the namespace is in the yamls so we’ll need to update those.

**Comment by arey** [comment]
Ok thus we may keep `spring-petclinic` and just rename `spring-pet-clinic`
