### ISSUE TITLE
Update services to run inside k8s

### ISSUE THREAD

**Issue by tscrypter** [spring-petclinic/spring-petclinic-cloud#2]

**Comment by arey** [comment]
Hi @tscrypter
Did you find some time to work on this change?

**Comment by rebla** [comment]
The config is still for docker not for k8s

**Comment by arey** [comment]
You're right @rebla. While waiting for a working version, you could check the https://github.com/odedia/spring-petclinic-microservices fork

@tscrypter are you planning to take in charge the dev? If you're agree, I could propose to @odedia to help us. Let me know.

**Comment by arey** [comment]
We look at some contributors to run the Spring Petclinic Microservices into K8S

**Comment by odedia** [comment]
Happy to assist with that.

**Comment by arey** [comment]
Great @odedia : you're welcome! I'm not familiar with k8s. Before to work on the upcoming changes, we may first discuss about what we have to do.

In the issue https://github.com/spring-petclinic/spring-petclinic-microservices/issues/138  @tscrypter give us some guidelines:

1.  Replace `spring-cloud-starter-netflix-eureka-client` with `Spring Cloud Kubernetes DiscoveryClient` 
2. Replace the `Spring Cloud Config Server` by `K8s ConfigMaps` (see the Baeldung's blog: https://www.baeldung.com/spring-cloud-kubernetes)
3.  Complete the `readme.md`

We may have to create a fork of the https://github.com/spring-petclinic/spring-petclinic-microservices-config repository. Let me know.

Are you ok for this proposal?

**Comment by mszarlinski** [comment]
Hi, there is already version of PetClinic hosted on Istio: https://github.com/saturnism/spring-petclinic-gcp @odedia it might be interested for you

**Comment by odedia** [comment]
> Great @odedia : you're welcome! I'm not familiar with k8s. Before to work on the upcoming changes, we may first discuss about what we have to do.
> 
> In the issue [spring-petclinic/spring-petclinic-microservices#138](https://github.com/spring-petclinic/spring-petclinic-microservices/issues/138) @tscrypter give us some guidelines:
> 
> 1. Replace `spring-cloud-starter-netflix-eureka-client` with `Spring Cloud Kubernetes DiscoveryClient`
> 2. Replace the `Spring Cloud Config Server` by `K8s ConfigMaps` (see the Baeldung's blog: https://www.baeldung.com/spring-cloud-kubernetes)
> 3. Complete the `readme.md`
> 
> Are you ok for this proposal?
>We may have to create a fork of the https://github.com/spring-petclinic/spring-petclinic-microservices-config repository. Let me know.

Hi @arey ,

1 and 2 are implemented in my own repository. It also includes the option to deploy the same code to Cloud Foundry, so it's a nice way to show how the same code can run on two different platforms with only dependency and config changes.
README does need some work.

Would you like me  to create a new fork as baseline?

@mszarlinski Thanks for that repo link, looks very interesting. I'll dig into his implementation. I've always enjoyed saturnism's talks. Some components there are Google specific so I might not use it as is.

**Comment by arey** [comment]
@odedia  I've synced this repo with the `spring-petclinic-microservices` one (Spring Boot 2.3.1, layered JAR). 
Does it possible to report your changes to `spring-petclinic-kubernetes`? 
If we support Cloud Foundry deployment, does the name `spring-petclinic-kubernetes` remains appropriate? I have a doubt.

**Comment by odedia** [comment]
It’s the same repo for both, just different maven profiles. Perhaps it would make sense to have a more generic name such as spring-petclinic-platforms.

**Comment by odedia** [comment]
PR was submitted.
It includes the following:
1. Using Spring Boot 2.3's `mvn spring-boot:build-image` feature which uses Cloud Native Buildpacks to build layers images automatically.
2. Supports deploying to Cloud Foundry.
3. Supports deploying to Kubernetes.
4. Supports integration with free Wavefront monitoring+tracing for Spring Boot applications.
5. Bumped JDK to version 11
