### ISSUE TITLE
how to deploy any war file or any html file into spring petclinic, is it possible? how to deploy anything by usnig this spring petclinic projetc

### ISSUE THREAD

**Issue by gopi1111** [spring-petclinic/spring-petclinic-cloud#47]
how to deploy any war file or any html file into spring petclinic, is it possible? 
how to deploy anything by usnig this spring petclinic project can any please tell me the steps or procedure

**Comment by arey** [comment]
Hi @gopi1111 This Spring Cloud version of the Spring Petclinic sample application is based on Spring Boot and auto-executable JARs. It does not use WAR file.
For a more simple version, I recommend your to try the original version: https://github.com/spring-projects/spring-petclinic

**Comment by arey** [comment]
Please reopen if required
