### ISSUE TITLE
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.18.10 <= 1.20.5

### ISSUE THREAD

**Issue by Jeeppler** [spring-petclinic/spring-petclinic-cloud#54]
I tried to install the Helm Chart on Minikube and get the following error:

~~~
$ helm install spring-petclinic-cloud Platform9-Community/spring-petclinic-cloud --namespace spring-petclinic --create-namespace
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.18.10 <= 1.20.5 which is incompatible with Kubernetes v1.26.3
~~~

**Comment by arey** [comment]
Hi @Jeeppler. It looks like this helm chart comes from the `https://github.com/Platform9-Community/spring-petclinic-cloud` repository, a fork of this one. I'm adding its author @ddieruf to the conversation. Maybe an adaptation is required to work on your kubernetes version?
By the way, did you try the ` helm template --validate` command line?

**Comment by Jeeppler** [comment]
@arey thanks for the quick reply. You are correct, I used Helm chart based on the `https://github.com/Platform9-Community/spring-petclinic-cloud` repository.

Is there a Helm Chart based on this repository?

> By the way, did you try the  helm template --validate command line?

No

**Comment by arey** [comment]
Just for setting the database: https://github.com/spring-petclinic/spring-petclinic-cloud/tree/master#settings-up-databases-with-helm

**Comment by arey** [comment]
Please reopen if required
