### ISSUE TITLE
Consider Wavefront integration

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-cloud#6]
Following a discussion with @maciejwalkowiak https://github.com/spring-petclinic/spring-petclinic-data-jdbc/pull/4#issuecomment-628883249, it could make sense to integrate Wavefront into the k8s version of Petclinic.

@odedia has already implement a fork here: https://github.com/odedia/spring-petclinic-microservices

**Comment by odedia** [comment]
PR #7 Integrates with Wavefront.

**Comment by arey** [comment]
PR #7 merged. Thanks @odedia
