### ISSUE TITLE
Switch to the spring-petclinic-cloud-config repo

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-cloud#8]
Following the exchanges carried out in the pull request https://github.com/spring-petclinic/spring-petclinic-cloud/pull/7, the  https://github.com/spring-petclinic/spring-petclinic-cloud-config repository has been created to manage the project configuration.
@odedia may now move its own repo https://github.com/odedia/spring-petclinic-microservices-config to this new one.

**Comment by odedia** [comment]
Done

**Comment by arey** [comment]
Thanks @odedia. 
I was wondering if the name `spring-cloud-petclinic` (instead of `spring-petclinic-cloud`) wouldn't make more sense. What do you think about?

**Comment by odedia** [comment]
I think it could get confusing because "Spring Cloud" means something else for Spring developers. With spring-petclinic-cloud we're just stating this is a cloud-based version of spring-petclinic (similar to -microservices, -local etc.)

**Comment by arey** [comment]
You're right: Spring Petclinic Microservices is also based upon Spring Cloud. `spring-cloud-petclinic`sounds better, but it's confusing and not very coherent. Keeping its name.
